objects/Exercise__c.object
<CustomObject>
    <description>List of exercises however a user will be working on a single exercise at any given time</description>
    <label>Exercise</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Exercise Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exercises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/z_FieldDescription__c.object
<CustomObject>
    <description>Created by the Metadata API</description>
    <label>SObjectField</label>
    <nameField>
        <label>SObjectField Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/z_SchemaTemp__c.object
<CustomObject>
    <description>Created by the Metadata API</description>
    <fields>
        <fullName>Exercise__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exercise</label>
        <referenceTo>Exercise__c</referenceTo>
        <relationshipLabel>z_SchemaTemp</relationshipLabel>
        <relationshipName>z_SchemaTemp</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Snapshot_Status__c</fullName>
        <label>Snapshot Status</label>
        <picklist>
            <picklistValues>
                <fullName>Old</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>fieldname__c</fullName>
        <label>fieldname</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>objid__c</fullName>
        <label>objid</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>objname__c</fullName>
        <label>objname</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>z_SchemaTemp</label>
    <nameField>
        <label>z_SchemaTemp</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/z_BatchableMetadataDump2.cls
global with sharing class z_BatchableMetadataDump2 implements Database.Batchable<SObject>, Database.Stateful {

    global Boolean executeBatch3;
    global Id exerciseId;
    global String snapshotType;
    global Boolean isDeleteData;

    global z_BatchableMetadataDump2() {
        // flag if z_BatchableMetadataDump2 is executed after this class is completed
       this(false, null, null, false);
    }
    
    global z_BatchableMetadataDump2(Boolean executeBatch3) {
        this(false, null, null, false);
    }
    
    global z_BatchableMetadataDump2(Boolean executeBatch3, Id exerciseId, String snapshotType, Boolean isDeleteData) {
        this.executeBatch3 = executeBatch3;
        this.exerciseId = exerciseId;
        this.snapshotType = snapshotType;
        this.isDeleteData = isDeleteData;
    }

    global database.querylocator start(Database.BatchableContext BC) {
        // z_BatchableMetadataDump1 should be executed before this call is called. Otherwize error
        return Database.getQueryLocator([Select objname__c, fieldname__c, objid__c 
                from z_SchemaTemp__c where Exercise__c = :exerciseId AND Snapshot_Status__c = :snapshotType]);
    }

    global void execute(Database.BatchableContext BC, SObject[] scope){
        List<z_FieldDescription__c> records = new List<z_FieldDescription__c>();
        for(SObject record : scope) {
            z_SchemaTemp__c schema = (z_SchemaTemp__c) record;
            records.add(z_DescribeHelper.createFieldDescriptionRecord(schema.objid__c, schema.objname__c, schema.fieldname__c));
        }
        // create z_FieldDescritption__c records
        insert records;
        delete scope;
    }
    
    global void finish(Database.BatchableContext BC){
        /*if(!executeBatch3)
            return;
            
        Datetime dt = System.now();
        String coreExpression = z_Util.convertToStringForScheduler(dt.addMinutes(2));
        System.schedule('z_BatchableMetadataDump3', coreExpression, new z_SchedulableBatchableMetadataDump3());*/
        
        Database.executeBatch(new z_BatchableMetadataDump3(exerciseId, snapshotType, isDeleteData));     
    }      
}