objects/Exercise__c.object
<CustomObject>
    <description>List of exercises however a user will be working on a single exercise at any given time</description>
    <fields>
        <fullName>ActiveTasks__c</fullName>
        <label>ActiveTasks</label>
        <summaryFilterItems>
            <field>Task__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </summaryFilterItems>
        <summaryForeignKey>Task__c.Exercise__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Body__c</fullName>
        <description>Detail info on exercise objectives and goals.</description>
        <label>Body</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <label>Summary</label>
        <length>550</length>
        <type>LongTextArea</type>
    </fields>
    <label>Exercise</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Exercise Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exercises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ElearningExercisesController.cls
// author: soe@soe.im
public class ElearningExercisesController {

    // constructor
    public ElearningExercisesController() {}
    
    public String getPageHeader() {
        return 'ExerciseListings';
    }
    
    public List<Exercise__c> getExercises() {
        List<Exercise__c> exercises = [SELECT Id, Name, Body__c, Summary__c, Status__c, Sequence__c, ActiveTasks__c FROM Exercise__c ORDER BY Status__c ASC, Sequence__c ASC];
        
        return exercises;
    }
    
    @isTest
    public static void ElearningExercisesControllerTest() {
    
        test.startTest();
        
        ElearningExercisesController cont = new ElearningExercisesController();
        cont.getPageHeader();
        
        Exercise__c e1 = new Exercise__c(Body__c = 'body', Sequence__c = 1, Status__c = 'Active');
        Insert e1;
        Exercise__c e2 = new Exercise__c(Body__c = 'body', Sequence__c = 2, Status__c = 'Inactive');
        Insert e2;
        Exercise__c e3 = new Exercise__c(Body__c = 'body', Sequence__c = 3, Status__c = 'Active');
        Insert e3;

        
        List<Exercise__c> exercises = cont.getExercises();

        System.assertEquals(exercises[0].Id, e1.Id);
        System.assertEquals(exercises[1].Id, e3.Id);
        System.assertEquals(exercises[2].Id, e2.Id);
        test.stopTest();
    }
}