objects/Exercise__c.object
<CustomObject>
    <description>List of exercises however a user will be working on a single exercise at any given time</description>
    <label>Exercise</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Exercise Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exercises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/z_MetaDumpSetting__c.object
<CustomObject>
    <description>Created by the Metadata API</description>
    <fields>
        <fullName>Exercise__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exercise</label>
        <referenceTo>Exercise__c</referenceTo>
        <relationshipLabel>Settings</relationshipLabel>
        <relationshipName>Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>name__c</fullName>
        <label>name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Setting</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Setting</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/z_SchemaTemp__c.object
<CustomObject>
    <description>Created by the Metadata API</description>
    <fields>
        <fullName>Exercise__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exercise</label>
        <referenceTo>Exercise__c</referenceTo>
        <relationshipLabel>z_SchemaTemp</relationshipLabel>
        <relationshipName>z_SchemaTemp</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Snapshot_Status__c</fullName>
        <label>Snapshot Status</label>
        <picklist>
            <picklistValues>
                <fullName>Old</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>objname__c</fullName>
        <label>objname</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>z_SchemaTemp</label>
    <nameField>
        <label>z_SchemaTemp</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/z_SObjectDescription__c.object
<CustomObject>
    <fields>
        <fullName>Exercise__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exercise</label>
        <referenceTo>Exercise__c</referenceTo>
        <relationshipLabel>SObject</relationshipLabel>
        <relationshipName>SObject</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Snapshot_Status__c</fullName>
        <label>Snapshot Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Old</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SObject</label>
    <nameField>
        <label>SObject Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/z_Util.cls
public with sharing class z_Util {
    
    static public void log(String str) {
        System.debug(logginglevel.INFO, str);
    }
    
    // Seconds  Minutes  Hours  Day_of_month  Month  Day_of_week  optional_year
    static public String convertToStringForScheduler(Datetime dt) {
        return dt.second() + ' ' + dt.minute() + ' ' + dt.hour() + ' ' + dt.day() + ' ' + dt.month() + ' ' + '?' + ' ' + dt.year();
    }
    
    static public Id executeBatchableMetadataDump1(boolean executeDump2) {
        prepareMetadataDump(null, null);
        // scope must be 1 because of governer limit
        return Database.executeBatch(new z_BatchableMetadataDump1(executeDump2), 1);
    }
    
    static public Id executeBatchableMetadataDump1(boolean executeDump2, Id exerciseId, String snapshotType, Boolean isDeleteData) {
        prepareMetadataDump(exerciseId, snapshotType);
        // scope must be 1 because of governer limit
        return Database.executeBatch(new z_BatchableMetadataDump1(executeDump2, exerciseId, snapshotType, isDeleteData), 1);
    }   

    static public id executeBatchableMetadataDump2(boolean executeDump3) {
        // scope must be 10 because of governer limit       
        return Database.executeBatch(new z_BatchableMetadataDump2(executeDump3), 10);
    }

    static public id executeBatchableMetadataDump3() {
        // scope must be 10 because of governer limit       
        return Database.executeBatch(new z_BatchableMetadataDump3(), 100);
    }
    
    static public void cleanData1(Id exerciseId, String snapshotType) {       
        List<SObject> objs = [Select id from z_SchemaTemp__c where Exercise__c = :exerciseId AND Snapshot_Status__c = :snapshotType limit 10000];
        if(objs.size() == 0)
            return;

        delete objs;
    }   
    
    static public void cleanData2(Id exerciseId, String snapshotType) {
        List<SObject> objs = [Select id from z_SObjectDescription__c where Exercise__c = :exerciseId AND Snapshot_Status__c = :snapshotType limit 10000];
        if(objs.size() == 0)
            return;

        delete objs;
    }   

    
    static public void prepareMetadataDump(Id exerciseId, String snapshotType) {
        cleanData1(exerciseId, snapshotType);
        cleanData2(exerciseId, snapshotType);

        List<z_MetaDumpSetting__c> settings = [Select id, name__c From z_MetaDumpSetting__c where Exercise__c = :exerciseId limit 10000];

        List<z_SchemaTemp__c> records = new List<z_SchemaTemp__c>();        
        for(z_MetaDumpSetting__c setting : [Select id, name__c From z_MetaDumpSetting__c where Exercise__c = :exerciseId]) {
            records.add(new z_SchemaTemp__c(objname__c = setting.name__c, Exercise__c =  exerciseId, Snapshot_Status__c = snapshotType));
        }
        insert records;
    }   
    
}