objects/Exercise__c.object
<CustomObject>
    <description>List of exercises however a user will be working on a single exercise at any given time</description>
    <label>Exercise</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Exercise Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exercises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/z_ChildRelationship__c.object
<CustomObject>
    <description>Created by the Metadata API</description>
    <fields>
        <fullName>childobjectname__c</fullName>
        <label>Child SObject Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>z_ChildSObjectDescription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Child SObject</label>
        <referenceTo>z_SObjectDescription__c</referenceTo>
        <relationshipLabel>ChildRelations (z_ChildSObjectDescription)</relationshipLabel>
        <relationshipName>z_ChildRelationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>z_ParentSObjectDescription__c</fullName>
        <label>Parent SObject</label>
        <referenceTo>z_SObjectDescription__c</referenceTo>
        <relationshipLabel>ChildRelations (z_ParentSObjectDescription)</relationshipLabel>
        <relationshipName>z_ChildRelationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ChildRelation</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>ChildRelation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ChildRelations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/z_MetaDumpSetting__c.object
<CustomObject>
    <description>Created by the Metadata API</description>
    <fields>
        <fullName>Exercise__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exercise</label>
        <referenceTo>Exercise__c</referenceTo>
        <relationshipLabel>Settings</relationshipLabel>
        <relationshipName>Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>name__c</fullName>
        <label>name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Setting</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Setting</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/z_SObjectDescription__c.object
<CustomObject>
    <fields>
        <fullName>Exercise__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exercise</label>
        <referenceTo>Exercise__c</referenceTo>
        <relationshipLabel>SObject</relationshipLabel>
        <relationshipName>SObject</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Snapshot_Status__c</fullName>
        <label>Snapshot Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Old</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SObject</label>
    <nameField>
        <label>SObject Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/z_BatchableMetadataDump3.cls
global with sharing class z_BatchableMetadataDump3 implements Database.Batchable<SObject>,Database.AllowsCallouts, Database.Stateful {
    global Id exerciseId;
    global String snapshotType;
    global Boolean isDeleteData;
    
    global z_BatchableMetadataDump3(){
        this(null, null, false);
    }
    
    global z_BatchableMetadataDump3(Id exerciseId, String snapshotType, Boolean isDeleteData){
        this.exerciseId = exerciseId;
        this.snapshotType = snapshotType;
        this.isDeleteData = isDeleteData;
    }
    
    // z_BatchableMetadataDump2 should be executed before this call
    global database.querylocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([Select z_ChildSObjectDescription__c, childobjectname__c 
                From z_ChildRelationship__c where z_ParentSObjectDescription__r.Snapshot_Status__c =:snapshotType AND z_ParentSObjectDescription__r.Exercise__c = :exerciseId]);
    }

    global void execute(Database.BatchableContext BC, SObject[] scope){
        List<z_ChildRelationship__c> records = new List<z_ChildRelationship__c>();

        for(SObject record : scope) {
            z_ChildRelationship__c schema = (z_ChildRelationship__c) record;
            String objname = schema.childobjectname__c;
            
            List<z_SObjectDescription__c> tmps = [Select id From z_SObjectDescription__c Where name =: objname AND Exercise__c =:exerciseId AND Snapshot_Status__c = :snapshotType];
            if(tmps.size() == 0)
                continue;
            
            schema.z_ChildSObjectDescription__c = tmps[0].id;
            records.add(schema);
        }

        update records;
    }
    
    global void finish(Database.BatchableContext BC){
    	//ResetMetadata rm = new ResetMetadata(exerciseId);
    	//Check if isDeleteData is set to true. If true, then delete large data
    	if(isDeleteData != null && isDeleteData){
    		//Delete large data
    		List<z_MetaDumpSetting__c> lstSetting = [Select Id,Name__c from z_MetaDumpSetting__c where Exercise__c = :exerciseId];
    		if(lstSetting != null && lstSetting.size() > 0){
    			List<String> lstObjects = new List<String>();
    			for(z_MetaDumpSetting__c sett: lstSetting){
    				lstObjects.add(sett.Name__c);
    			}
    			Database.executeBatch(new DeleteLargeDataBatch('All', Userinfo.getUserId(), lstObjects));
    		}
    	}
    }      

}