objects/Exercise__c.object
<CustomObject>
    <description>List of exercises however a user will be working on a single exercise at any given time</description>
    <fields>
        <fullName>Body__c</fullName>
        <description>Detail info on exercise objectives and goals.</description>
        <label>Body</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VideoID__c</fullName>
        <label>VideoID</label>
        <length>220</length>
        <type>Text</type>
    </fields>
    <label>Exercise</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Exercise Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exercises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Step__c.object
<CustomObject>
    <description>Steps are associated with tasks.</description>
    <fields>
        <fullName>Body__c</fullName>
        <description>Detail step by step instructions</description>
        <label>Body</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description for each step, that will be shown in the Detail Modal in the eLearning Page</description>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Steps</relationshipLabel>
        <relationshipName>Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>VideoID__c</fullName>
        <description>add the youtube video ID only</description>
        <inlineHelpText>Only youtube ID.</inlineHelpText>
        <label>VideoID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Step</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Step Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Task__c.object
<CustomObject>
    <description>There can be one or more tasks associated with an exercise.</description>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Exercise__c</fullName>
        <label>Exercise</label>
        <referenceTo>Exercise__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ElearningLandingController_Test.cls
/**
 * @author Manish
 * @purpose Test class for ElearningLandingController
 */
@isTest
private class ElearningLandingController_Test{
    
    static testMethod void myUnitTest() {
        
        //list of task to insert
        List<Task__c> listOfTask= new List<Task__c>();
        
        //list of step to insert
        List<Step__c> listOfStep = new List<Step__c>();
        
        //lets create a test exercise
        Exercise__c testExc = new Exercise__c(Status__c = 'Active', Sequence__c = 1, Body__c = 'Test Some Data');
        Database.insert(testExc);
        
        // some test tasks
        Task__c testTask1 = new Task__c(Exercise__c = testExc.id, Sequence__c = 1, Body__c = 'Test Task 1', Status__c = 'Active');
        Task__c testTask2 = new Task__c(Exercise__c = testExc.id, Sequence__c = 2, Body__c = 'Test Task 2', Status__c = 'Active');
        listOfTask.add(testTask1);
        listOfTask.add(testTask2);
        Database.insert(listOfTask);
        
        //some test steps 
        Step__c testStep1 = new Step__c( Task__c = testTask1.id, Body__c = 'test step 1', Sequence__c = 1, VideoID__c = 'testId', Description__c = 'some test description');
        Step__c testStep2 = new Step__c( Task__c = testTask1.id, Body__c = 'test step 2', Sequence__c = 2, VideoID__c = 'testId2', Description__c = 'some test description2');
        listOfStep.add(testStep1);
        listOfStep.add(testStep2);
        Database.insert(listOfStep);
        
        test.startTest();
            //set the current page
            PageReference landingPage = new PageReference('/apex/eLearningLandingPage?id='+testExc.id);
            test.setCurrentPage(landingPage);
            
            //initializing the controller
            ElearningLandingController ctrl = new ElearningLandingController();
            
            //calling the method to retrieve all the exercise
            //ctrl.getExercise();
            
            //this will set the current task to be the one with sequence 1
            System.assert(ctrl.currentTask.id ==  testTask1.id);
            
            //lets change the step
            ctrl.changeToNextStep();
            
            //this will change the current step to one with sequence 2
            System.assert(ctrl.currentStep.id == testStep2.id);
            
            //lets change the task
            ctrl.changeToNextTask();
            
            //this will change the current task to one with sequence 2
            System.assert(ctrl.currentTask.id == testTask2.id);
            
        test.stopTest();
        
        
    }
    
    
}